#!name=Spotify Plus
#!desc=Mở khóa một phần tính năng Premium. Khuyến nghị đăng nhập lại sau khi cài đặt. Không hỗ trợ chất lượng âm thanh cao cấp.
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  

[MITM]
hostname = %APPEND% spclient.wg.spotify.com, *spclient.spotify.com

[Script]
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js

spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0

spotify-qx-header = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-qx-header.js

[Header Rewrite]
# 移除if-none-match以防止304响应
^https:\/\/(spclient\.wg\.spotify\.com|.*-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match
