#!name=Spotify Plus
#!desc=Mở khóa một phần tính năng Premium. Khuyến nghị đăng nhập lại sau khi cài đặt. Không hỗ trợ chất lượng âm thanh cao cấp.
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  

[Header Rewrite]
# if-none-match返回304状态码，避免广告加载
http-request ^https:\/\/(spclient\.wg\.spotify\.com|guc3-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ header-del if-none-match

[MITM]
hostname = %APPEND% spclient.wg.spotify.com, guc3-spclient.spotify.com

[Script]
# 请求头拦截（去除广告等）
spotify-json = type=http-request,pattern=^https:\/\/(spclient\.wg\.spotify\.com|guc3-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js

# 响应体修改（模拟 Premium 状态）
spotify-proto = type=http-response,pattern=^https:\/\/(spclient\.wg\.spotify\.com|guc3-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0

# 兼容 Quantumult X
^https:\/\/(spclient\.wg\.spotify\.com|guc3-spclient\.spotify\.com(:443)?)\/user-customization-service\/v1\/customize$ url script-request-header https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-qx-header.js
^https:\/\/(spclient\.wg\.spotify\.com|guc3-spclient\.spotify\.com(:443)?)\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$ url script-response-body https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js
^https:\/\/(spclient\.wg\.spotify\.com|guc3-spclient\.spotify\.com(:443)?)\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/ url script-request-header https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js
