#!name=Spotify Premium 
#!desc=Mở khóa một phần tính năng Premium. Khuyến nghị đăng nhập lại sau khi cài đặt. Không hỗ trợ chất lượng âm thanh cao cấp.
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  
#!author=app2smile[https://github.com/app2smile]
#!category=iKeLee
#!openUrl=https://apps.apple.com/app/id324684580
#!tag=去广告
[Script]
JSON处理 = type=http-request, pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/, script-path=https://kelee.one/Resource/Script/Spotify/Spotify_remove_ads.js, timeout=10

Proto处理 = type=http-response, pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$, script-path=https://kelee.one/Resource/Script/Spotify/Spotify_proto.js, requires-body=true, binary-body-mode=true, timeout=10

[MITM]
hostname = %APPEND% spclient.wg.spotify.com
