#!name=Spotify Plus - Nightmarket
#!desc=Mở khóa một phần tính năng Premium. Khuyến nghị đăng nhập lại sau khi cài đặt. Không hỗ trợ chất lượng âm thanh cao cấp.
# 💬 Discord: https://discord.gg/juY9tw5AJY  
# 🚀 Released by: Nightmarket Server  

[Script]

#SpotifyPremium #hostname = spclient.wg.spotify.com spotify-json = type=http-request,pattern=^https://spclient.wg.spotify.com/(artistview/v1/artist|album-entity-view/v2/album)/,requires-body=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-json.js

spotify-proto = type=http-response,pattern=^https://spclient.wg.spotify.com/(bootstrap/v1/bootstrap|user-customization-service/v1/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/app2smile/rules/master/js/spotify-proto.js,script-update-interval=0

[MITM] hostname = %APPEND% spclient.wg.spotify.com
